# Generated by Django 4.1.7 on 2023-07-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ganalytics", "0002_analyticdata_delete_analyticsdata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analyticdata",
            name="avg_page_load_time_sec",
        ),
        migrations.RemoveField(
            model_name="analyticdata",
            name="country_page_sessions",
        ),
        migrations.RemoveField(
            model_name="analyticdata",
            name="landing_new_sessions",
        ),
    ]
