# Generated by Django 4.1.7 on 2023-07-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ganalytics", "0003_remove_analyticdata_avg_page_load_time_sec_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analyticdata",
            name="date",
        ),
    ]
