# Generated by Django 4.1.7 on 2023-08-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ganalytics",
            "0006_rename_country_benchmark_new_users_analyticdata_country_users",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="analyticdata",
            old_name="g_date",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="analyticdata",
            name="country_users",
        ),
    ]
