# Generated by Django 4.1.7 on 2023-08-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ganalytics", "0007_rename_g_date_analyticdata_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analyticdata",
            old_name="date",
            new_name="g_date",
        ),
    ]
