# Generated by Django 4.1.7 on 2023-08-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ganalytics", "0008_rename_date_analyticdata_g_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticdata",
            name="country_users",
            field=models.CharField(default="null", max_length=100),
        ),
    ]
