# Generated by Django 4.1.7 on 2023-08-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ganalytics", "0010_remove_analyticdata_country_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticdata",
            name="months",
            field=models.CharField(default="null", max_length=100),
        ),
    ]
