# Generated by Django 4.1.7 on 2023-08-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ganalytics", "0011_analyticdata_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticdata",
            name="country_users",
            field=models.CharField(default="null", max_length=100),
        ),
    ]
