# Generated by Django 4.1.7 on 2023-08-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ganalytics", "0013_remove_analyticdata_country_benchmark_bounce_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analyticdata",
            name="bucket_page_views",
        ),
    ]
