# Generated by Django 4.1.7 on 2023-08-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ganalytics", "0014_remove_analyticdata_bucket_page_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticdata",
            name="country_page_session",
            field=models.CharField(default="null", max_length=100),
        ),
    ]
