# Generated by Django 4.1.7 on 2023-08-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ganalytics", "0015_analyticdata_country_page_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticdata",
            name="country_bounce_rate1",
            field=models.CharField(default="null", max_length=100),
        ),
    ]
