# Generated by Django 4.1.7 on 2023-08-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ganalytics", "0016_analyticdata_country_bounce_rate1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analyticdata",
            old_name="country_bounce_rate1",
            new_name="country_bounce1_rate",
        ),
        migrations.AddField(
            model_name="analyticdata",
            name="landing_new_session",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="affinity_category_reach",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="all_website_average_position",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="all_website_bounce_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="all_website_clicks",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="all_website_ctr",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="all_website_device_category",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="all_website_impressions",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="all_website_pages_session",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="all_website_sessions",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="audience",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="audience_avg_session_duration",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="audience_bounce_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="audience_new_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="audience_pages_session",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="audience_sessions",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="audience_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="avg_session_duration_reach",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="avg_time_on_page",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="bounce_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="bounce_rate_reach",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="browser_bounce_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="browser_pages_session",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="bucket_session",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="campaign_bounce_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="campaign_campaign_id",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="campaign_clicks",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="campaign_cost",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="campaign_cpc",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="campaign_pages_session",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="campaign_sessions",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="campaign_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="country",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="country_average_position",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="country_avg_session_duration",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="country_bounce_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="country_clicks",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="country_ctr",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="country_impressions",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="country_new_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="country_pages_session",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="country_sessions",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="default_channel_avg_session_duration",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="default_channel_bounce_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="default_channel_grouping",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="default_channel_new_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="default_channel_pages_session",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="default_channel_sessions",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="default_channel_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="device_bounce_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="device_category",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="device_new_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="device_page_session",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="device_sessions",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="device_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="event_category",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="event_total_events",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="event_unique_events",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="exit_percent",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="final_url",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="goal_completion_location",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="goal_completions",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="landing_avg_session_duration",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="landing_bounce_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="landing_new_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="landing_page",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="landing_page_session",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="landing_sessions",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="language",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="language_avg_session_duration",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="language_bounce_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="language_new_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="language_pages_session",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="language_sessions",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="language_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="market_avg_session_duration",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="market_bounce_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="market_new_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="market_pages_session",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="market_segment",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="market_sessions",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="market_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="medium_avg_session_duration",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="medium_bounce_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="medium_new_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="medium_pages_session",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="medium_sessions",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="medium_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="mobile_device_avg_session_duration",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="mobile_device_bounce_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="mobile_device_info",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="mobile_device_new_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="mobile_device_sessions",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="mobile_device_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="new_users_reach",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="other_category",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="other_category_avg_session_duration",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="other_category_bounce_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="other_category_new_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="other_category_pages_session",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="other_category_sessions",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="other_category_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="page",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="page_bounce_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="page_event",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="page_exit",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="page_path_level1",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="page_per_views",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="page_total_events",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="page_unique_events",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="page_view",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="pages_session_reach",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="per_hour",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="per_hour_avg_session_duration",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="per_hour_bounce_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="per_hour_new_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="per_hour_pages_session",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="per_hour_sessions",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="per_hour_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="search_avg_position",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="search_clicks",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="search_ctr",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="search_impressions",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="search_query",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="session_duration_bucket",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="sessions_reach",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="site_search_avg_session_duration",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="site_search_bounce_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="site_search_e_commerce_conversion_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="site_search_new_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="site_search_page_session",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="site_search_revenue",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="site_search_transaction",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="source_medium",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="unique_page_view",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="url_bounce_rate",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="url_clicks",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="url_cost",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="url_cpc",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="url_page_session",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="url_sessions",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="url_users",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="analyticdata",
            name="users_reach",
            field=models.CharField(default="null", max_length=100),
        ),
    ]
